# nginx.conf
server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Сжатие
    gzip on;
    gzip_types text/html text/css text/javascript application/javascript;

    # Кэширование
    location ~* \.(html|css|js)$ {
        expires 1d;
        add_header Cache-Control "public, immutable";
    }

    # Основной блок
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Проверка здоровья
    location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }
}
